import type { Event, PaymentReceipt } from '../types/api';

export const mockEvent: Event = {
  id: 'evt-1',
  event_id: 'evt-1',
  title: 'Indore Tech Summit',
  description: 'A conference about modern software.',
  category_id: 'cat-1',
  category_name: 'Conference',
  event_type: 'OFFLINE',
  venue: 'Community Hall',
  city: 'Indore',
  state: 'Madhya Pradesh',
  country: 'India',
  ticket_price: '100.00',
  is_free: false,
  capacity: 50,
  available_seats: 10,
  start_datetime: '2030-12-31T10:00:00+00:00',
  registration_status: 'OPEN',
  organizer_name: 'Test Organizer',
  convenience_fee: '5.00',
  gateway_fee: '2.00',
  banner_url: 'https://cdn.example.test/banner.jpg',
  images: [{ id: 'img-1', file: '', media_id: 'media-1', media_url: 'https://cdn.example.test/gallery-1.jpg' }],
  videos: [{ id: 'vid-1', file: '', media_id: 'media-2', media_url: 'https://cdn.example.test/video.mp4' }],
};

export const mockOnlineEvent: Event = {
  ...mockEvent,
  event_id: 'evt-online',
  id: 'evt-online',
  title: 'Online Workshop',
  event_type: 'ONLINE',
  meeting_link: 'https://meet.example.test/room',
  venue: undefined,
  city: undefined,
  images: [],
  videos: [],
};

export const mockReceipt: PaymentReceipt = {
  payment_id: 'payment-1',
  receipt_number: 'RCPT-123',
  event_title: 'Receipt event',
  category_name: 'Conference',
  buyer_name: 'Test Buyer',
  buyer_phone: '9876543210',
  ticket_price: '100.00',
  discount: '0.00',
  convenience_fee: '5.00',
  gateway_fee: '2.00',
  amount: '107.00',
  payment_status: 'SUCCESS',
  completed_at: '2026-08-01T10:00:00Z',
  event_type: 'OFFLINE',
  order_id: 'order-1',
  venue: 'Community Hall',
  city: 'Indore',
  state: 'Madhya Pradesh',
};
