"""Initial schema

Revision ID: ddfbcb826b3a
Revises: 
Create Date: 2026-07-24 13:25:52.029063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddfbcb826b3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_admin_status'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('category',
    sa.Column('category_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('total_events', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_registrations', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_tickets_sold', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('name IS NOT NULL', name='ck_category_name_not_null'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coupon',
    sa.Column('coupon_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flat_discount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_used', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_discount_given', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('coupon_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('organizer',
    sa.Column('organizer_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizer_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('total_events', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('active_events', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_registrations', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_tickets_sold', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('platform_fee_generated', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_organizer_status'),
    sa.PrimaryKeyConstraint('organizer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=False),
    sa.Column('organizer_email', sa.String(length=255), nullable=False),
    sa.Column('organizer_phone', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('is_free', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('gateway_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('total_registrations', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_tickets_sold', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=True),
    sa.Column('registration_status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('ONLINE','OFFLINE','HYBRID')", name='ck_event_type'),
    sa.CheckConstraint("registration_status IN ('OPEN','CLOSED')", name='ck_event_registration_status'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','COMPLETED','ARCHIVED')", name='ck_event_status'),
    sa.CheckConstraint('(NOT is_free) OR ticket_price = 0', name='ck_event_is_free_ticket_price'),
    sa.CheckConstraint('available_seats >= 0 AND available_seats <= capacity', name='ck_event_available_seats_range'),
    sa.CheckConstraint('capacity > 0', name='ck_event_capacity_positive'),
    sa.CheckConstraint('convenience_fee >= 0', name='ck_event_convenience_fee_nonnegative'),
    sa.CheckConstraint('gateway_fee >= 0', name='ck_event_gateway_fee_nonnegative'),
    sa.CheckConstraint('registration_end IS NULL OR registration_start IS NULL OR registration_end > registration_start', name='ck_event_registration_window'),
    sa.CheckConstraint('ticket_price >= 0', name='ck_event_ticket_price_nonnegative'),
    sa.CheckConstraint('total_registrations >= 0', name='ck_event_total_registrations_nonnegative'),
    sa.CheckConstraint('total_sales >= 0', name='ck_event_total_sales_nonnegative'),
    sa.CheckConstraint('total_tickets_sold >= 0', name='ck_event_total_tickets_sold_nonnegative'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizer.organizer_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('idx_event_keywords', ['keywords'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_event_search', ['city', 'category_name', 'event_type'], unique=False)
        batch_op.create_index('idx_event_status', ['status', 'registration_status'], unique=False)

    op.create_table('registration',
    sa.Column('registration_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_city', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('registrant_name', sa.String(length=255), nullable=False),
    sa.Column('registrant_email', sa.String(length=255), nullable=True),
    sa.Column('registrant_phone', sa.String(length=50), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('gateway_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reservation_status', sa.String(length=20), server_default=sa.text("'RESERVED'"), nullable=True),
    sa.Column('registration_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("registration_status IN ('PENDING','CONFIRMED','FAILED')", name='ck_registration_status'),
    sa.CheckConstraint("reservation_status IN ('RESERVED','EXPIRED')", name='ck_registration_reservation_status'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_registration_discount_amount_nonnegative'),
    sa.CheckConstraint('seats_booked > 0', name='ck_registration_seats_booked_positive'),
    sa.CheckConstraint('ticket_price >= 0', name='ck_registration_ticket_price_nonnegative'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.coupon_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizer.organizer_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_index('idx_registration_event', ['event_id'], unique=False)
        batch_op.create_index('idx_registration_org', ['organizer_id'], unique=False)

    op.create_table('payment',
    sa.Column('payment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=255), nullable=True),
    sa.Column('receipt_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('gateway_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default=sa.text("'INITIATED'"), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_status IN ('INITIATED','SUCCESS','FAILED')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.registration_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id'),
    sa.UniqueConstraint('receipt_number'),
    sa.UniqueConstraint('registration_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_org', ['organizer_id'], unique=False)
        batch_op.create_index('idx_payment_status', ['payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_status')
        batch_op.drop_index('idx_payment_org')

    op.drop_table('payment')
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_index('idx_registration_org')
        batch_op.drop_index('idx_registration_event')

    op.drop_table('registration')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('idx_event_status')
        batch_op.drop_index('idx_event_search')
        batch_op.drop_index('idx_event_keywords', postgresql_using='gin')

    op.drop_table('event')
    op.drop_table('organizer')
    op.drop_table('coupon')
    op.drop_table('category')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_entity')

    op.drop_table('audit_log')
    op.drop_table('admin')
    # ### end Alembic commands ###
